<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1303;CA2007;CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <ProjectReference Include="..\..\src\Moongazing.OrionVault\Moongazing.OrionVault.csproj" />
    <ProjectReference Include="..\..\src\Moongazing.OrionVault.EntityFrameworkCore\Moongazing.OrionVault.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
